spring:
#  r2dbc:
#    # Tell Spring to look for the schema script on the test classpath.
#    schema:
#      - "classpath:schema.sql"
  sql:
    init:
      mode: always
      schema-locations: "classpath:schema.sql"


s3:
  local: true
  bucket: "my-test-bucket"
#  endpoint: "some.endpoint.com"
#  port: 9999
  access-key: "some-access-key"
  secret-key: "some-secret-key"
  max-connections: 100
  connection-timeout: 60
  socket-timeout: 60

scanner:
  local: true
#  host: "some.scanner.host"
#  port: 9999

file-server:
  local: true
#  secure: false
#  host: "some.file.server.host"
#  port: 8080
#  connection-timeout-ms: 10000
#  response-timeout-seconds: 600