spring:
  profiles:
    active: ${PROFILE:test}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # this makes sure that writing to the disk is limited to 10MB
  webflux:
    multipart:
      max-in-memory-size: 1MB
      max-disk-usage-per-part: 10MB  # Small allowance for multipart parsing
      streaming: true


#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.http: DEBUG
#    reactor.netty: DEBUG