s3:
  endpoint: ${S3_ENDPOINT}
  port: ${S3_PORT}
  access-key: ${S3_ACCESS_KEY}
  secret-key: ${S3_SECRET_KEY}
  region: ${S3_REGION}
  bucket: ${S3_BUCKET}
  max-connections: ${S3_MAX_CONNECTIONS}
  connection-timeout: ${S3_CONNECTION_TIMEOUT}
  socket-timeout: ${S3_SOCKET_TIMEOUT}

scanner:
  host: ${SCANNER_HOST}
  port: ${SCANNER_PORT}

file-server:
  secure: ${FILE_SERVER_SECURE:false}
  host: ${FILE_SERVER_HOST}
  port: ${FILE_SERVER_PORT}
  connection-timeout-ms: ${FILE_SERVER_CONNECTION_TIMEOUT_MS}
  response-timeout-seconds: ${FILE_SERVER_RESPONSE_TIMEOUT_SECONDS}